name: Docker

on:
  push:
    branches:
      - '*'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      # Call the custom action in this repo at /action.yml
      - uses: ./
        with:
          entrypoint: './build.sh'

      - name: Run in OVMF
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu-system
          timeout --foreground 20 make run
